# Generated by Django 5.2.6 on 2025-09-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="cidade",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cpf",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="telefone",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_admin",
            field=models.BooleanField(
                default=True,
                help_text="Designa se o usuário é um administrador",
                verbose_name="Administrador",
            ),
        ),
    ]
