# Generated by Django 5.2.6 on 2025-09-13 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['marca', 'modelo', 'placa']},
        ),
        migrations.RemoveField(
            model_name='carro',
            name='preco',
        ),
        migrations.AddField(
            model_name='carro',
            name='diaria',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='locatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carros_alugados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(default=1, max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$', message='Placa inválida.')]),
            preserve_default=False,
        ),
    ]
