# Generated by Django 5.2.6 on 2025-09-13 16:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_alter_carro_options_remove_carro_preco_carro_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='diaria',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
