# Generated by Django 5.2.6 on 2025-09-16 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_alter_carro_diaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='id',
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(help_text='Ex.: ABC1234 ou ABC1D23', max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{3}\\d{4}$|^[A-Z]{3}\\d[A-Z]\\d{2}$', message='Placa inválida.')]),
        ),
    ]
